name: Windows Server 2019 RDP

on: workflow_dispatch

jobs:

  build:

    runs-on: windows-2019

    timeout-minutes: unlimited

    steps:

    - name: Download Ngrok.

      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/arakurumi/Free-RDP/main/ngrok.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/arakurumi/Free-RDP/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/arakurumi/Free-RDP/main/loop.bat -OutFile loop.bat
        
    - name: Extract Ngrok File.

      run: Expand-Archive ngrok.zip

    - name: Connect Ngrok.

      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

      env:

        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Windows Server 2019 RDP.

      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        
    - name: Tunnel.

      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region=ap 3389"'

    - name: Connect RDP.

      run: cmd /c start.bat

    - name: Checking Windows Server 2019 RDP.

      run: cmd /c loop.bat
